# Args: <output_dir> <blend_file> <haven_dir> <cam_file> <boat_dir> <mountain_dir> <buoy_dir>
{
  "version": 3,
  "setup": {
    "blender_install_path": ""
  },
  "modules": [
    {
      "module": "main.Initializer",
      "config":{
        "global": {
          "output_dir": "<args:0>"
        }
      }
    },
    {
      "module": "loader.BlendLoader",
      "config": {
        "path": "<args:1>"
      }
    },
    {
      "module": "loader.HavenEnvironmentLoader",
      "config": {
         "data_path": "<args:2>"
      }
    },
    {
      "module": "camera.CameraLoader",
      "config": {
        "path": "<args:3>",
        "file_format": "location rotation/value",
        "intrinsics": {
          "fov": 1.248,
          "clip_end": 200000
        }
      }
    },   
    {
      "module": "customModules.BoatRandomizer",
      "config": {
        "boats": 25,
        "boats_close": {
          "provider": "sampler.Value",
          "type": "int",
          "min": 1,
          "max": 5
        },
        "path": "<args:4>"
      }
    },
    {
      "module": "customModules.MountainRandomizer",
      "config": {
        "path": "<args:5>"
      }
    },
    {
      "module": "customModules.BuoyRandomizer",
      "config": {
        "buoys": 25,
        "buoys_close": {
          "provider": "sampler.Value",
          "type": "int",
          "min": 0,
          "max": 5
        },
        "path": "<args:6>"
      }
    },
    {
      "module": "manipulators.EntityManipulator",
      "config": {
        "selector": {
          "provider": "getter.Entity",
          "conditions": {
            "name": 'Boat.*',
            "type": "MESH"
          }
        },
        "location": {
          "provider": "sampler.Uniform3d",
          "max":[2250, 3000, 20],
          "min":[-2250, 150, 0]
        },
        "scale": [50,50,50]
      }
    },
    {
      "module": "manipulators.EntityManipulator",
      "config": {
        "selector": {
          "provider": "getter.Entity",
          "conditions": {
            "name": 'Boat_close.*',
            "type": "MESH"
          }
        },
        "location": {
          "provider": "sampler.Uniform3d",
          "max":[440, 500, 20],
          "min":[-440, 150, 0]
        },
        "scale": [50,50,50]
      }
    },
    {
      "module": "manipulators.EntityManipulator",
      "config": {
        "selector": {
          "provider": "getter.Entity",
          "conditions": {
            "name": 'Mountain.*',
            "type": "MESH"
          }
        },
        "location": {
          "provider": "sampler.Uniform3d",
          "max":[4000, 3500, -100],
          "min":[-4000, 3500, -300]
        },
        "scale": {
          "provider": "sampler.Same3d",
          "max": 1500,
          "min": 500
        }
      }
    },
    {
      "module": "manipulators.EntityManipulator",
      "config": {
        "selector": {
          "provider": "getter.Entity",
          "conditions": {
            "name": 'Buoy.*',
            "type": "MESH"
          }
        },
        "location": {
          "provider": "sampler.Uniform3d",
          "max":[2250, 3000, 6],
          "min":[-2250, 150, -2]
        },
        "scale": [10,10,10]
      }
    },
    {
      "module": "manipulators.EntityManipulator",
      "config": {
        "selector": {
          "provider": "getter.Entity",
          "conditions": {
            "name": 'Buoy_close.*',
            "type": "MESH"
          }
        },
        "location": {
          "provider": "sampler.Uniform3d",
          "max":[440, 500, 6],
          "min":[-440, 150, -2]
        },
        "scale": [10,10,10]
      }
    },
    {
      "module": "manipulators.WorldManipulator",
      "config": {
        "cf_set_world_category_id": 0
      }
    },
    {
      "module": "customModules.OceanModule",
      "config": {
        "ocean": "OceanB"
      }
    },
    {
      "module": "renderer.RgbRenderer",
      "config": {
        "output_key": "colors",
        "output_is_temp": False,
        "simplify_subdivision_render": 0
      }
    },
    {
      "module": "renderer.SegMapRenderer",
      "config": {
        "map_by": ["class"],
        "default_values": {"class": 2},
        "output_is_temp": False,
        "use_alpha": True
      }
    },
    {
      "module": "customModules.SegToPngModule",
      "config":{
        "path": "<args:0>",
        "startFrame": 1,
        "endFrame": 2
      }
    }
  ]
}
